# CodeRabbit Configuration
# Documentation: https://docs.coderabbit.ai/guides/configure-coderabbit

language: "en-US"
early_access: false

reviews:
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  tools:
    ruff:
      enabled: true
    mypy:
      enabled: true
    eslint:
      enabled: true
    prettier:
      enabled: true
  path_filters:
    - "!**/*.md"
    - "!**/*.txt"
    - "!**/package-lock.json"
    - "!**/yarn.lock"
  instructions: |
    - Focus on correctness, security, and performance impacts
    - Require tests or explain why coverage is not needed
    - Verify logging, telemetry, and error handling paths
    - Validate API contracts, schemas, and migrations
    - Flag missing docs or runbooks for operational work

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto
